batch_size: 8
cfg: DMFNET_MEMB3D_TRAIN
ckpt_dir: ./ckpts
criterion: attention_dice_loss
criterion_kwargs:
  eps: 1.0e-05
  weight_type: identity
d_threshold: 20
d_uniform: false
dataset: Memb3DDataset
gpu: 0,1,2,3
name: DMFNET_MEMB3D_TRAIN
net: DMFNet
net_params:
  conv_channels: 128
  groups: 16
  in_channels: 1
  n_first: 32
  norm: sync_bn
  out_class: 8
num_epochs: 20
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.005
  weight_decay: 1.0e-05
restore: ''
save_freq: 5
seed: 1024
show_image_freq: -1
show_loss_freq: -1
start_iter: 0
test_data_dir: dataset/test
test_embryos: ('181210plc1p2',)
test_transforms: Compose([ Pad([205, 285, 144]), Resize((208, 288, 144)), NumpyType((np.float32,
  np.int64)), ])
train_data_dir: dataset/train
train_embryos: ('170614plc1p1', '170704plc1p1')
train_transforms: Compose([ RandCrop((128,128,128)), RandomRotation(10), RandomFlip(0),
  NumpyType((np.float32, np.int64, np.int64)) ])
valid_data_dir: dataset/validation
valid_freq: 5
workers: 8
